
backend = "consul"
backend_nodes = ["localhost:8500"]
datacenter = "dc1"
scheme = "http"
cert = ""
key = ""
ca_cert = ""

interfaces = ["eth0", "eth1", "en0", "lo0"]
service_interface = "en0"

template = "template1"
